### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by lafuentei** [VIS-2129-F2020/ilafuente-vis#1]
Both the Rmd and html files are ammended and ready. My focus was mainly in exploring graphs as you asked for, but I expect to produce more interesting information and extract more custom data and variables for the next assignments! (the Quant part). As a student feedback, I felt very upset about the software during the process, but in the end I started to feel comfortable and more curious about it. The methodology was a bit painful but worked :)

**Comment by bauranov** [comment]
Great work! Everything is super clear and the plots are intuitive. Keep up the good work, this an awesome start.
