### ISSUE TITLE
Assignment 3 is ready

### ISSUE THREAD

**Issue by lafuentei** [VIS-2129-F2020/ilafuente-vis#3]
Assignment 3 is ready for grading. Thank you. https://vis-2129-f2020.github.io/ilafuente-vis/

**Comment by bauranov** [comment]
Good work, everything looks great. One thing I'd mention is that the titles are confusing (Metric 1, Metric 3, Metric 14, Metric 7...)

**Comment by lafuentei** [comment]
Yes thank you! I wanted to refer to the Syllabus guidelines (which 6 out of the 22 metrics available I was doing), but it got messy.
