### ISSUE TITLE
Assignment 4 is ready for grading

### ISSUE THREAD

**Issue by lafuentei** [VIS-2129-F2020/ilafuente-vis#4]
Thank you! Link:

https://vis-2129-f2020.github.io/ilafuente-vis/filename

**Comment by lafuentei** [comment]
Sorry I meant https://vis-2129-f2020.github.io/ilafuente-vis/assignment4

**Comment by bauranov** [comment]
Amazing work, very informative. This looks like the beginning of a research paper :)
